### ISSUE TITLE
Is SecureJson Functional?

### ISSUE THREAD

**Issue by mapeebles** [nthmost/python-secureconfig#2]
I have tried the two examples, one form the readme and one from the actual securejson.py file and I get different exceptions. (I can use the SecureConfigParser as documented).

My basic test is:
from secureconfig import SecureJson
configpath = './config.json.enc'
config = SecureJson.from_file('.keys', filepath=configpath)
config.set('credentials', 'password', 'better_password')
fh = open(configpath, 'w')
config.write(fh)
fh.close()

OUTPUT:
----------
File "sec_json.py", line 4, in <module>
    config = SecureJson.from_file('.keys', filepath=configpath)
  File "/VENV/lib/python2.7/site-packages/secureconfig/cryptkeeper.py", line 63, in from_file
    return cls(*args, **kwargs)
  File "/VENV/lib/python2.7/site-packages/secureconfig/baseclass.py", line 69, in __init__
    self._fill(self._decrypt(rawtxt))
  File "/VENV/lib/python2.7/site-packages/secureconfig/baseclass.py", line 83, in _decrypt
    return self.ck.crypter.decrypt(buf)
  File "/VENV/lib/python2.7/site-packages/cryptography/fernet.py", line 82, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken

when running the example in the securejson.py, it returns: 
  File "sec_json.py", line 25, in <module>
    sjson.write("test_securejson.json.enc")
  File "/VENV/lib/python2.7/site-packages/secureconfig/baseclass.py", line 161, in write
    fh.write(buf)
AttributeError: 'str' object has no attribute 'write'

Any ideas?  Is there some other setup required?
Thanks

**Comment by Tilendor** [comment]
In the example it is calling .write on the string path to the file.  The method is expecting a file handle, not a string.  I was able to get this to work:

#~!/usr/bin/oython

import os, sys, getopt
from json import dumps, loads
from secureconfig import SecureJson

def main(argv):

   signal_phone_number = argv[0]
   aliases = argv[1:]

   config_path = 'config.json.enc'
   config = SecureJson.from_file('key')

   config.cfg['signal_phone_number'] = signal_phone_number
   config.cfg['aliases'] = aliases

   print(config)

   with open(config_path,'w+') as f:
      SecureJson.write(config,f)

   new_config = SecureJson.from_file('key', filepath=config_path)
   print new_config

if __name__ == "__main__":
   main(sys.argv[1:])
