### ISSUE TITLE
Fix tests in master

### ISSUE THREAD

**Issue by nthmost** [nthmost/python-secureconfig#7]
Since merging in a nice PR to get python3 compatibility (https://github.com/nthmost/python-secureconfig/pull/6), a bunch of the tests are now broken.

**Comment by nthmost** [comment]
After merging, doesn't seem like all the tests work yet.

```==================================================================================== test session starts ====================================================================================
platform darwin -- Python 3.8.1, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /Users/nthmost/projects/git/python-secureconfig
collected 23 items                                                                                                                                                                          

tests/test_cryptkeeper.py .........                                                                                                                                                   [ 39%]
tests/test_secureconfig.py .....                                                                                                                                                      [ 60%]
tests/test_secureconfigparser.py ....F                                                                                                                                                [ 82%]
tests/test_securestring.py .FF.                                                                                                                                                       [100%]

========================================================================================= FAILURES ==========================================================================================
_________________________________________________________________ TestSecureConfigParser.test_wrong_ck_raises_InvalidToken __________________________________________________________________

self = <test_secureconfigparser.TestSecureConfigParser testMethod=test_wrong_ck_raises_InvalidToken>

    def test_wrong_ck_raises_InvalidToken(self):
        scfg = SecureConfigParser(ck=self.ck_wrong)
        scfg.read(TEST_INI_OUTFILE)
>       self.assertRaises(InvalidToken, scfg.get(testd['section'], testd['enc']['key']))
E       TypeError: 'NoneType' object is not callable

tests/test_secureconfigparser.py:129: TypeError
--------------------------------------------------------------------------------- Captured stdout teardown ----------------------------------------------------------------------------------
Created files: 
['/Users/nthmost/projects/git/python-secureconfig/tests/unchanged.ini', '/Users/nthmost/projects/git/python-secureconfig/tests/new_encrypted_values.ini']
_____________________________________________________________________ TestSecureString.test_SecureString_zeroes_on_del ______________________________________________________________________

self = <test_securestring.TestSecureString testMethod=test_SecureString_zeroes_on_del>

    def test_SecureString_zeroes_on_del(self):
        ss = SecureString("it's a secret23 to everybody")
        ctuple = learn_mem(ss._string)
        del(ss)
        gc.collect()
        result = get_from_mem(ctuple)
        try:
            print(ss)
            assert False
        except UnboundLocalError:
            assert True
    
>       assert result.find('23') == -1
E       TypeError: argument should be integer or bytes-like object, not 'str'

tests/test_securestring.py:57: TypeError
----------------------------------------------------------------------------------- Captured stderr call ------------------------------------------------------------------------------------
Exception ignored in: <function SecureString.__del__ at 0x10bbe5940>
Traceback (most recent call last):
  File "/Users/nthmost/.local/share/virtualenvs/python-secureconfig-qFHhn7Tl/lib/python3.8/site-packages/secureconfig-0.1.2-py3.8-macosx-10.15-x86_64.egg/secureconfig/securestring.py", line 18, in __del__
  File "zeromem.pyx", line 4, in secureconfig.zeromem.zeromem (secureconfig/zeromem.c:684)
TypeError: expected bytes, str found
_____________________________________________________________________ TestSecureString.test_burn_method_zeroes__string ______________________________________________________________________

self = <test_securestring.TestSecureString testMethod=test_burn_method_zeroes__string>

    def test_burn_method_zeroes__string(self):
        ss = SecureString("of all the things I've lost, I miss my mind the most")
        ctuple = learn_mem(ss._string)
>       ss.burn()

tests/test_securestring.py:36: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/Users/nthmost/.local/share/virtualenvs/python-secureconfig-qFHhn7Tl/lib/python3.8/site-packages/secureconfig-0.1.2-py3.8-macosx-10.15-x86_64.egg/secureconfig/securestring.py:14: in burn
    zeromem(self._string)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: expected bytes, str found

zeromem.pyx:4: TypeError
===================================================================================== warnings summary ======================================================================================
/Users/nthmost/.local/share/virtualenvs/python-secureconfig-qFHhn7Tl/lib/python3.8/site-packages/secureconfig-0.1.2-py3.8-macosx-10.15-x86_64.egg/secureconfig/zeromem.py:3
  /Users/nthmost/.local/share/virtualenvs/python-secureconfig-qFHhn7Tl/lib/python3.8/site-packages/secureconfig-0.1.2-py3.8-macosx-10.15-x86_64.egg/secureconfig/zeromem.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

tests/test_cryptkeeper.py::TestCryptKeeper::test_StringCK_key_eq_key
  /Users/nthmost/projects/git/python-secureconfig/tests/test_cryptkeeper.py:70: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(self.string_ck.key, TEST_KEYSTRING)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================= 3 failed, 20 passed, 2 warnings in 0.40s ==========================================================================
Exception ignored in: <function SecureString.__del__ at 0x10bbe5940>
Traceback (most recent call last):
  File "/Users/nthmost/.local/share/virtualenvs/python-secureconfig-qFHhn7Tl/lib/python3.8/site-packages/secureconfig-0.1.2-py3.8-macosx-10.15-x86_64.egg/secureconfig/securestring.py", line 18, in __del__
  File "zeromem.pyx", line 4, in secureconfig.zeromem.zeromem (secureconfig/zeromem.c:684)
TypeError: expected bytes, str found
(python-secureconfig) nthmost@Naomis-MBP ~/p/g/python-secureconfig (master) [0|1]> 
```

**Comment by nthmost** [comment]
I very much appreciate your efforts on this @andy-shady-org and I'm sorry I don't have more time to work on it.

For the record (since it is not stated elsewhere, I don't think), I want to make sure `python-secureconfig` works in all python versions between python 3.8 and either 3.5 or 3.6 (very willing to shift upwards here, since Mac OSX and Ubuntu have been on 3.6 for many years).

**Comment by andy-shady-org** [comment]
Ive looked at all of these today for you, and there is one outstanding issue I believe.

(venv-python38) [11:37]:andy@maccy:~/python-secureconfig/tests (master) (70) $ python ./test_cryptkeeper.py 
.........
----------------------------------------------------------------------
Ran 9 tests in 0.040s

OK


(venv-python38) [11:37]:andy@maccy:~/python-secureconfig/tests (master) (71) $ python ./test_secureconfig.py 
Creating JSON file
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK


(venv-python38) [11:38]:andy@maccy:~/python-secureconfig/tests (master) (72) $ python ./test_secureconfigparser.py 
.....Created files: 
['/Users/andy/python-secureconfig/tests/unchanged.ini', '/Users/andy/python-secureconfig/tests/cfg_test_out.ini']

----------------------------------------------------------------------
Ran 5 tests in 0.053s

OK

**Comment by andy-shady-org** [comment]
the final outstanding issue is:

(venv-python38) [11:38]:andy@maccy:~/python-secureconfig/tests (master) (73) $ python ./test_securestring.py 
.EE.
======================================================================
ERROR: test_SecureString_zeroes_on_del (__main__.TestSecureString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_securestring.py", line 64, in test_SecureString_zeroes_on_del
    assert result.find('23') == -1
TypeError: argument should be integer or bytes-like object, not 'str'

======================================================================
ERROR: test_burn_method_zeroes__string (__main__.TestSecureString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_securestring.py", line 46, in test_burn_method_zeroes__string
    assert result.find('things') == -1
TypeError: argument should be integer or bytes-like object, not 'str'

----------------------------------------------------------------------
Ran 4 tests in 0.008s

FAILED (errors=2)



I believe this is to do with ctypes returning a bytestring:

In [32]: a = 'this is a test'                                                                                                                                                                                                                                            

In [33]: loc = id(a)                                                                                                                                                                                                                                                     

In [34]: size = sys.getsizeof(a)                                                                                                                                                                                                                                         

In [35]: type(a)                                                                                                                                                                                                                                                         
Out[35]: str

In [36]: b = ctypes.string_at(loc, size)                                                                                                                                                                                                                                 

In [37]: b                                                                                                                                                                                                                                                               
Out[37]: b"\x01\x00\x00\x00\x00\x00\x00\x00\x90\xf2\x08\x0c\x01\x00\x00\x00\x0e\x00\x00\x00\x00\x00\x00\x00\xa2`\xa6%EG\x1c\x18\xe4 = 'thi\x00\x00\x00\x00\x00\x00\x00\x00this is a test\x00"



this means that 'result' is a bytestring, and the test uses .find() to try and find a substring within this. Im not sure if the ctype behaviour changed and used to return a str, and not something else. Id need to look into this more.

**Comment by andy-shady-org** [comment]
(venv-python38) [12:49]:andy@maccy:~/python-secureconfig/tests (master) (106) $ python ./test_securestring.py 
....
----------------------------------------------------------------------
Ran 4 tests in 0.009s

OK

probably want to check this...

**Comment by andy-shady-org** [comment]
If you are happy, you can close this issue, and push new version ?

**Comment by nthmost** [comment]
Checking now...

**Comment by nthmost** [comment]
I'm putting up a pypi package now.  Removed py2/3 compat code while i was add it.  Thanks for the nudge!!
